version: '3.8'

services:

  application:
    image: sagakkb/practice:latest
    container_name: application
    ports:
      - "8080:8080"
    networks:
      - back_net
    volumes:
      - ./logs:/var/logs
    restart: always
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - 'dev-database-data:/var/lib/mysql'
    networks:
      - back_net
    restart: always

volumes:
  dev-database-data:
    driver: local

networks:
  back_net:
    driver: bridge
